name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - trigger.txt  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t supruniukmaksym/simple-server:latest .

      - name: Debug DOCKER_USERNAME
        run: echo "Username = ${{ secrets.DOCKER_USERNAME }}"

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-server:latest

