name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - trigger.txt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set IMAGE_TAG (timestamp)
        run: echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Set IMAGE_NAME
        run: echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/simple-server:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "$IMAGE_NAME" .

      - name: Push Docker image
        run: docker push "$IMAGE_NAME"

      - name: Update image tag in deployment.yaml
        run: |
          sed -i 's|image: .*|image: '"$IMAGE_NAME"'|' k8s/deployment.yaml

      - name: Commit and push updated deployment.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push