name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths:
      - trigger.txt  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set IMAGE_NAME env var
        run: echo "IMAGE_NAME=$(echo '${{ secrets.DOCKER_USERNAME }}' | tr -d '\n\r')/simple-server:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t "$IMAGE_NAME" .

      - name: Push Docker image
        run: docker push "$IMAGE_NAME"

